# Generated by Django 5.2.4 on 2025-07-20 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        db_index=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                ("description", models.TextField()),
                ("source_url", models.URLField(default="", unique=True)),
                ("last_scraped", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "price"], name="products_pr_name_dd5c99_idx"
                    ),
                    models.Index(
                        fields=["last_scraped"], name="products_pr_last_sc_a3f4e3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Trend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trending_score", models.FloatField(db_index=True, default=0.0)),
                ("price_velocity", models.FloatField(default=0.0)),
                ("search_volume", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-trending_score"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source", models.CharField(default="unknown", max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-recorded_at"],
                        name="products_pr_product_84f8c9_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="products_pr_recorde_b1d7b3_idx"
                    ),
                ],
            },
        ),
    ]
