# Generated by Django 5.2.4 on 2025-07-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="url",
        ),
        migrations.AddField(
            model_name="product",
            name="last_scraped",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0.0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="source_url",
            field=models.URLField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name", "price"], name="products_pr_name_dd5c99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["last_scraped"], name="products_pr_last_sc_a3f4e3_idx"
            ),
        ),
    ]
