# Generated by Django 5.2.4 on 2025-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_current_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="trend",
            name="price_change_24h",
            field=models.FloatField(default=0.0),
        ),
    ]
