# Generated by Django 5.2.4 on 2025-07-20 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_image_url_remove_product_url_and_more"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="price",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="sale_price",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="start_date",
        ),
        migrations.AddField(
            model_name="sale",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sale",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["product", "created_at"], name="sales_sale_product_33bffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["user", "created_at"], name="sales_sale_user_id_0426bc_idx"
            ),
        ),
    ]
