name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install flake8 black

      - name: Lint with flake8
        run: flake8 backend/ --config=backend/.flake8

      - name: Format with black
        run: black --check backend/

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Lint with eslint
        run: npm run lint --prefix frontend

      - name: Format with prettier
        run: npm run format --prefix frontend -- --check

      - name: Run backend tests
        run: |
          cd backend
          python manage.py test

      - name: Run frontend tests
        run: npm test --prefix frontend

      - name: Build frontend
        run: npm run build --prefix frontend
